---
- name: install jdk 8
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - deploy
- name: install jdk 8
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openjdk-8-jdk
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deploy
- name: Add RuleChains Repo
  yum_repository:
    name: "{{ rulechainsrepo.name }}"
    description: "{{ rulechainsrepo.name }}"
    baseurl: "{{ rulechainsrepo.baseurl }}"
    gpgcheck: "{{ rulechainsrepo.gpgcheck }}"
    repo_gpgcheck: "{{ rulechainsrepo.repo_gpgcheck }}"
    enabled: "{{ rulechainsrepo.enabled }}"
    metadata_expire: 1200
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - deploy
- name: install the latest version of RuleChains
  package:
    name: RuleChains
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - deploy
- name: install the latest updates
  package:
    name: "*"
    state: latest    
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - deploy
- name: install the latest updates
  package:
    name: "*"
    state: latest    
    force_apt_get: True
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deploy
- name: Add config template
  template:
    src: "{{ playbook_dir }}/templates/config/rulechains-config.yml.j2"
    dest: /usr/local/etc/rulechains/rulechains-config.yml
    mode: 0644
  tags:
    - deploy
    