---
- name: install jdk 8
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
- name: Add Rundeck Repo
  yum_repository:
    name: "{{ rulechainsrepo.name }}"
    description: "{{ rulechainsrepo.name }}"
    baseurl: "{{ rulechainsrepo.baseurl }}"
    gpgcheck: "{{ rulechainsrepo.gpgcheck }}"
    repo_gpgcheck: "{{ rulechainsrepo.repo_gpgcheck }}"
    enabled: "{{ rulechainsrepo.enabled }}"
- name: install the latest version of RuleChains
  package:
    name: RuleChains
    state: latest
- name: install the latest updates
  package:
    name: *
    state: latest    
- name: Add config template
  template:
    src: "{{ playbook_dir }}/templates/config/rulechains-config.yml.j2"
    dest: /usr/local/etc/rulechains/rulechains-config.yml
    mode: 0644