---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  vars:
    app_name: "{{ lookup('ini', 'appBaseName type=properties file=../gradle.properties') }}"
    app_version: "{{ lookup('ini', 'appVersion type=properties file=../gradle.properties') }}"
  gather_facts: no
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - setup: # aka gather_facts
  tasks:
#    - name: pull an image
#      docker_image:
#        name: pacur/centos-7
#      tags:
#        - provision    
#    - name: Stop a container
#      docker_container:
#        name: "{{ inventory_hostname }}"
#        state: stopped
#      ignore_errors: yes
#      tags:
#        - provision
#    - name: remove container
#      docker_container:
#        name: "{{ inventory_hostname }}"
#        state: absent
#      ignore_errors: yes
#      tags:
#        - provision
#    - name: recreate a container
#      docker_container:
#        name: "{{ inventory_hostname }}"
#        image: pacur/centos-7
#        # recreate: yes
#        command: ["sleep", "infinity"]
#      tags:
#        - provision    
    - name: Test connection
      shell: ls
      register: testtask
      tags:
        - provision      
    - name: Some test task
      debug:
        msg: "I ran {{ testtask }}"
      tags:
        - provision
    - name: Install dumb init
      get_url:
        dest: /usr/bin/dumb-init
        url: https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
        mode: 0775
        validate_certs: no
      tags:
        - provision
        