---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  vars:
    app_name: "{{ lookup('ini', 'appBaseName type=properties file=../gradle.properties') }}"
    app_version: "{{ lookup('ini', 'appVersion type=properties file=../gradle.properties') }}"
  gather_facts: no
  roles:
    - role: sslcerts
      ssl_certs_generate_dh_param: true
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
      ssl_certs_common_name: "{{ansible_fqdn}}"
      tags:
        - provision
    - role: nginx
      nginx_configs:
        ssl:
          - ssl_certificate_key {{ssl_certs_privkey_path}}
          - ssl_certificate     {{ssl_certs_cert_path}}
          - ssl_dhparam         {{ssl_certs_dhparam_path}}
      nginx_sites:
        default:
          - listen 443 ssl
          - server_name _
          - root "/usr/share/nginx/html"
          - index index.html
      nginx_http_params:
        - sendfile "on"
        - tcp_nopush "on"
        - tcp_nodelay "on"
        - keepalive_timeout "65"
        - access_log "/var/log/nginx/access.log"
        - error_log "/var/log/nginx/error.log"
        - server_tokens off
        - types_hash_max_size 2048
        - client_max_body_size "3M"
      nginx_daemon_mode: "off"
      tags:
        - provision
  tasks:
    - name: Some task
      debug:
        msg: "I ran"
      tags:
        - provision