---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  vars:
    app_name: "{{ lookup('ini', 'appBaseName type=properties file=../gradle.properties') }}"
    app_version: "{{ lookup('ini', 'appVersion type=properties file=../gradle.properties') }}"
  gather_facts: no
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    tags:
      - provision      
  - setup: # aka gather_facts
    tags:
      - provision      
  tasks:
    - name: install jdk 8
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - openjdk-8-jdk
      tags:
        - provision
    - name: create package folder
      file:
        path: /tmp/debs
        state: "{{ item }}"
      with_items:
        - absent
        - directory
      tags:
        - provision
    - name: Copy package to remote host
      copy:
        src: "{{ item }}"
        dest: /tmp/debs
      with_fileglob:
        - "../build/libs/rulechains*.deb"
      tags:
        - provision
    - name: Find the rulechains package that was produced
      find:
        paths: "/tmp/debs"
        patterns: "rulechains*.deb"
      register: iffind
      tags:
        - provision
    - name: Install rulechains package
      package:
        name: "{{ item.path }}"
        state: present
      with_items: "{{ iffind.files|default([]) }}"
      register: rc_result
      tags:
        - provision
    - name: install the latest updates
      package:
        name: "*"
        state: latest
        force_apt_get: True
      tags:
        - provision
    - name: Add config template
      template:
        src: "{{ playbook_dir }}/templates/config/rulechains-config.yml.j2"
        dest: /usr/local/etc/rulechains/rulechains-config.yml
        mode: 0644
      tags:
        - provision