---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  vars:
    app_name: "{{ lookup('ini', 'appBaseName type=properties file=../gradle.properties') }}"
    app_version: "{{ lookup('ini', 'appVersion type=properties file=../gradle.properties') }}"
  tasks:
    - name: Build RuleChainsService
      include_tasks: build.yml
      tags:
        - build
    - name: Publish RuleChainsService
      include_tasks: publish.yml
      when: "deploy_env == 'Development'"
      tags:
        - publish
    - name: Provision RuleChainsService
      include_tasks: provision.yml
      when: "deploy_env == 'Development'"
      tags:
        - provision
    - name: Deploy RuleChainsService
      include_tasks: deploy.yml
      when: "deploy_env == 'Development'"
      tags:
        - deploy

