---
- hosts: "{{ target_hosts }}"
  gather_facts: "{{ gather_facts }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  vars:
    app_name: "{{ lookup('ini', 'appBaseName type=properties file=../gradle.properties') }}"
    app_version: "{{ lookup('ini', 'appVersion type=properties file=../gradle.properties') }}"
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    tags:
      - provision      
  - setup: # aka gather_facts
    tags:
      - provision      
  tasks:
    - name: Build RuleChainsService
      include_tasks: build.yml
      tags:
        - build
    - name: Publish RuleChainsService
      include_tasks: publish.yml
      when: "deploy_env == 'Production'"
      tags:
        - publish
    - name: Provision RuleChainsService
#      include_tasks: provision.yml
      include_tasks: altprovision.yml
      when: "deploy_env == 'Development'"
      tags:
        - provision
    - name: Deploy RuleChainsService
      include_tasks: deploy.yml
      when: "deploy_env == 'Development'"
      tags:
        - deploy
