---
- name: recreate a container
  docker_container:
    name: rulechainsservice
    image: phusion/baseimage:0.10.1
    state: started
    recreate: yes
    command: "/sbin/my_init"
    # command: ["sleep", "infinity"]
  tags:
    - provision    
 
    