---
- src: ssh://git@github.com/GulfCoastGreens/inventory.git
  version: master
  scm: git
  name: inventory
- src: geerlingguy.repo-epel
  version: 1.2.2
  name: repo-epel
- src: jdauphant.ssl-certs
  version: v1.4
  name: sslcerts
- src: jdauphant.nginx
  version: v2.15.2
  name: nginx
  nginx_http_params:
    - sendfile "on"
    - tcp_nopush "on"
    - tcp_nodelay "on"
    - keepalive_timeout "65"
    - access_log "/var/log/nginx/access.log"
    - error_log "/var/log/nginx/error.log"
    - server_tokens off
    - types_hash_max_size 2048
    - client_max_body_size "3M"
  tags:
    - deploy

